name: Test

on:
  - push
  - pull_request

jobs:
  # test-swift:
  #   name: Test (Swift)
  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - name: Run tests
  #       run: xcodebuild clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project ./Glance.xcodeproj -scheme Glance

  test-go:
    name: Test (Go)
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./HTMLConverter/

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Restore Go Modules cache
        id: go-mod-cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod/
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Run tests
        run: go test
